// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPW6-L_sdl9AEue1GPejShTrkauJlIyi4',
    appId: '1:983960271611:web:bd823988b0db46eb154e5e',
    messagingSenderId: '983960271611',
    projectId: 'latihan-firestore-140c9',
    authDomain: 'latihan-firestore-140c9.firebaseapp.com',
    storageBucket: 'latihan-firestore-140c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjxY2Aapm7-GqMNsuMnsbM2ehlxZG7EiA',
    appId: '1:983960271611:android:4dfa72ec89a318d0154e5e',
    messagingSenderId: '983960271611',
    projectId: 'latihan-firestore-140c9',
    storageBucket: 'latihan-firestore-140c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASwgz1crb3YzM1RiJopsNIMBmkLIXM278',
    appId: '1:983960271611:ios:799cb9745b42f9a7154e5e',
    messagingSenderId: '983960271611',
    projectId: 'latihan-firestore-140c9',
    storageBucket: 'latihan-firestore-140c9.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASwgz1crb3YzM1RiJopsNIMBmkLIXM278',
    appId: '1:983960271611:ios:799cb9745b42f9a7154e5e',
    messagingSenderId: '983960271611',
    projectId: 'latihan-firestore-140c9',
    storageBucket: 'latihan-firestore-140c9.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPW6-L_sdl9AEue1GPejShTrkauJlIyi4',
    appId: '1:983960271611:web:49d4de8099387f4f154e5e',
    messagingSenderId: '983960271611',
    projectId: 'latihan-firestore-140c9',
    authDomain: 'latihan-firestore-140c9.firebaseapp.com',
    storageBucket: 'latihan-firestore-140c9.appspot.com',
  );
}
