name: notes
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  file_selector: ^1.0.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_map: ^6.1.0
  geolocator: ^11.1.0
  google_maps_flutter: ^2.5.3
  http: ^1.2.1
  image_picker: ^1.0.8
  image_picker_for_web: ^3.0.4
  # image_preview: ^1.0.7
  path: ^1.8.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
