name: theme_switcher
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
# https://pub.dev/packages/animated_theme_switcher
  animated_theme_switcher: ^2.0.10
  day_night_switcher: ^0.2.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
